# Generated by Django 5.0.14 on 2026-05-28 08:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PinterestAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "cookies",
                    models.JSONField(
                        help_text="Original cookies array from browser extension"
                    ),
                ),
                (
                    "proxy",
                    models.CharField(
                        help_text="Format: http://username:password@ip:port or socks5://...",
                        max_length=512,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "webhook_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pinterest_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PinterestBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pinterest_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=512)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boards",
                        to="pinterest_app.pinterestaccount",
                    ),
                ),
            ],
        ),
    ]
