# Generated by Django 5.0.14 on 2026-05-28 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinterestboard',
            old_name='pinterest_id',
            new_name='board_id',
        ),
    ]
